version: '3.4'
services:
  api:
    container_name: api
    build: 
      context: ./api
      target: prod 
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
    - "8000:80"
    depends_on:
      - mysql
    environment:
      - PYTHONPATH=/api
    volumes:
      - ./api/api:/api:cached # TODO: Validate cache works as expected

  script_runner:
    container_name: script_runner
    build: 
      context: ./api
      target: dev
    command: "sleep infinity" # TODO: There must be a better way to start a container that just waits.
    environment:
      - API_TEST_URL=http://api/
      - PYTHONPATH=/api
      - OAUTHLIB_INSECURE_TRANSPORT=True
    volumes:
      - ./api/api:/api:cached # TODO: Validate cache works as expected
    depends_on:
      - api

  mysql:
    container_name: mysql
    hostname: mysql
    image: percona:5.7
    environment:
      MYSQL_DATABASE: initiative_planning
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - 3306:3306
