version: '3.4'
services:
  api:
    build: 
      context: ./api
      target: dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
    - "8000:80"
    volumes:
      - ./api/api:/api
